// <auto-generated />
using System;
using DreamDwellings.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DreamDwellings.Migrations
{
    [DbContext(typeof(DreamDwellingsDbContext))]
    [Migration("20240123174023_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DreamDwellings.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BathNumber")
                        .HasColumnType("numeric");

                    b.Property<int>("BedNumber")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HomeTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ListedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PurchasedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Sold")
                        .HasColumnType("boolean");

                    b.Property<decimal>("SquareFeet")
                        .HasColumnType("numeric");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeTypeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Homes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BathNumber = 2m,
                            BedNumber = 3,
                            City = "Franklin",
                            Description = "Welcome to this charming 3-bedroom, 2-bathroom home offering 1500 sq ft of comfortable living space. This residence boasts a spacious interior, perfect for both relaxation and entertainment. The well-appointed bedrooms provide ample space for rest, while the inviting common areas create a warm and welcoming atmosphere. With its desirable features and prime location, this home presents an ideal opportunity for a new chapter of comfortable living.",
                            HomeImage = "https://dhp.dreeshomes.com/cms/images/5vlwKrt_41I8s7yG-NZKFW?quality=80&width=1200",
                            HomeTypeId = 1,
                            ListedOn = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 450000,
                            Sold = false,
                            SquareFeet = 1500m,
                            StreetAddress = "123 Main St"
                        },
                        new
                        {
                            Id = 2,
                            BathNumber = 2.5m,
                            BedNumber = 4,
                            City = "Franklin",
                            Description = "Step into luxury with this stunning 4-bedroom, 2.5-bathroom home spanning across 2000 sq ft of modern elegance. The well-designed layout offers spacious living areas and an upgraded kitchen perfect for culinary enthusiasts. Unwind in the generous bedrooms, including a master suite with a private bath. With its impressive features and generous square footage, this home provides an exceptional blend of comfort and style, making it an ideal retreat for you and your family.",
                            HomeImage = "https://dhp.dreeshomes.com/cms/images/D-TyO6d0q1L9l-S5Jg6Ouw?quality=80&width=1200",
                            HomeTypeId = 1,
                            ListedOn = new DateTime(2023, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 292000,
                            Sold = false,
                            SquareFeet = 2000m,
                            StreetAddress = "456 Elm St"
                        },
                        new
                        {
                            Id = 3,
                            BathNumber = 2m,
                            BedNumber = 3,
                            City = "Brentwood",
                            Description = "Discover the perfect harmony of space and comfort in this inviting 3-bedroom, 2-bathroom home spanning 1800 sq ft. The well-designed layout creates a seamless flow between living and sleeping areas, providing both functionality and charm. Enjoy the tranquility of a spacious master suite, and relish the convenience of a thoughtfully designed kitchen. With its cozy ambiance and desirable features, this home offers a wonderful haven for relaxation and everyday living.",
                            HomeImage = "https://nhs-dynamic-secure.akamaized.net/Images/Homes/Drees/69096216-230623.jpg?maxwidth=900&maxheight=600&format=jpg&progressive=true",
                            HomeTypeId = 1,
                            ListedOn = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 399000,
                            Sold = false,
                            SquareFeet = 1800m,
                            StreetAddress = "789 Oak St"
                        },
                        new
                        {
                            Id = 4,
                            BathNumber = 3m,
                            BedNumber = 4,
                            City = "Brentwood",
                            Description = "Indulge in the spacious luxury of this captivating 4-bedroom, 3-bathroom home boasting an expansive 2200 sq ft floor plan. This residence is designed for both comfort and style, featuring generous bedrooms, including a lavish master suite with a private bath retreat. The open-concept living areas seamlessly connect, providing a perfect setting for gatherings and entertainment. With its impressive square footage and modern amenities, this home offers a blend of elegance and functionality, creating an inviting sanctuary for you and your family.",
                            HomeImage = "https://www.hersindex.com/wp-content/uploads/2020/04/Drees-Austin-Header-scaled.jpg",
                            HomeTypeId = 1,
                            ListedOn = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 299000,
                            Sold = false,
                            SquareFeet = 2200m,
                            StreetAddress = "101 Pine St"
                        },
                        new
                        {
                            Id = 5,
                            BathNumber = 2.5m,
                            BedNumber = 3,
                            City = "Smyrna",
                            Description = "Welcome to this delightful 3-bedroom, 2.5-bathroom home offering 1600 sq ft of cozy and efficient living space. The thoughtfully designed layout features a bright and airy atmosphere, blending practicality with style. Relax in the comfortable bedrooms, including a charming master suite with a convenient ensuite bath. With its modest yet well-utilized square footage, this home provides a perfect balance of comfort and modern living, creating a warm and inviting retreat for you and your loved ones.",
                            HomeImage = "https://www.dreeshomes.com/globalassets/production-ready/design---distinctive-design/lauren-ii-a_drees.jpg",
                            HomeTypeId = 1,
                            ListedOn = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 305000,
                            Sold = false,
                            SquareFeet = 1600m,
                            StreetAddress = "202 Maple St"
                        });
                });

            modelBuilder.Entity("DreamDwellings.Models.HomeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HomeTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeTypeName = "Single Family Home"
                        },
                        new
                        {
                            Id = 2,
                            HomeTypeName = "Condo"
                        },
                        new
                        {
                            Id = 3,
                            HomeTypeName = "Townhouse"
                        },
                        new
                        {
                            Id = 4,
                            HomeTypeName = "Apartment"
                        });
                });

            modelBuilder.Entity("DreamDwellings.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Phil",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Dunphy"
                        });
                });

            modelBuilder.Entity("DreamDwellings.Models.UserSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserSaves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeId = 1,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            HomeId = 3,
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            ConcurrencyStamp = "a8defec4-c0d5-40b8-9984-80803333380a",
                            Name = "Admin",
                            NormalizedName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0a35d64-ff51-4644-b569-d7274deb87c9",
                            Email = "phil@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEHX9hohnCocVFS8ywUPd2fZkf6QD5gzztv8vNJJuD/MXikpSghC9qoqa0O3lE4R7hw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "add298e2-41fe-4c70-8cde-55a0bfd2c731",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DreamDwellings.Models.Home", b =>
                {
                    b.HasOne("DreamDwellings.Models.HomeType", "HomeType")
                        .WithMany()
                        .HasForeignKey("HomeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamDwellings.Models.UserProfile", "HomeOwner")
                        .WithMany("OwnedHomes")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("HomeOwner");

                    b.Navigation("HomeType");
                });

            modelBuilder.Entity("DreamDwellings.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("DreamDwellings.Models.UserSave", b =>
                {
                    b.HasOne("DreamDwellings.Models.Home", "Home")
                        .WithMany("UserSaves")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DreamDwellings.Models.UserProfile", "UserProfile")
                        .WithMany("SavedHomes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Home");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DreamDwellings.Models.Home", b =>
                {
                    b.Navigation("UserSaves");
                });

            modelBuilder.Entity("DreamDwellings.Models.UserProfile", b =>
                {
                    b.Navigation("OwnedHomes");

                    b.Navigation("SavedHomes");
                });
#pragma warning restore 612, 618
        }
    }
}
